"""empty message

Revision ID: 0f478aefb7be
Revises: a24708dd261e
Create Date: 2025-04-27 13:09:22.789274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f478aefb7be'
down_revision = 'a24708dd261e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    return None
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llms', schema=None) as batch_op:
        batch_op.alter_column('group',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('category_embeddings', schema=None) as batch_op:
        batch_op.create_index('idx_avg_embedding', ['avg_embedding'], unique=False, postgresql_using='ivfflat')

    with op.batch_alter_table('arxiv_papers', schema=None) as batch_op:
        batch_op.create_index('idx_vector_embedding', ['vector_embedding'], unique=False, postgresql_using='ivfflat')

    op.create_table('question',
    sa.Column('question_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('question_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('answer_1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer_1_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer_2_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer_3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer_3_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer_4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer_4_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer_5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer_5_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('question_id', name='question_pkey')
    )
    op.create_table('courses',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('link', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
