"""Create arxiv_papers table

Revision ID: 37b515f9ef96
Revises: d83e00a32f0d
Create Date: 2025-04-27 00:42:53.022213

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector  # Đảm bảo rằng bạn đã cài đặt pgvector cho SQLAlchemy


# revision identifiers, used by Alembic.
revision = '37b515f9ef96'
down_revision = 'd83e00a32f0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'arxiv_papers',
        sa.Column('id', sa.Integer(), nullable=False),  # Cột ID
        sa.Column('title', sa.String(length=255), nullable=False),  # Cột Title
        sa.Column('question', sa.String(length=255), nullable=False),  # Cột Question
        sa.Column('link', sa.String(length=255), nullable=False),  # Cột Link
        sa.Column('category', sa.String(length=255), nullable=False),  # Cột Category
        sa.Column('abstract', sa.Text(), nullable=False),  # Cột Abstract
        sa.Column('vector_embedding', Vector(384), nullable=False),  # Cột vector_embedding (sử dụng pg_vector với chiều dài 768)
        sa.PrimaryKeyConstraint('id')  # Chỉ định ID là khóa chính
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llms', schema=None) as batch_op:
        batch_op.alter_column('group',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)

    op.create_table('courses',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('link', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('question',
    sa.Column('question_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('question_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('answer_1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer_1_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer_2_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer_3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer_3_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer_4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer_4_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer_5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer_5_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('question_id', name='question_pkey')
    )
    op.drop_table('arxiv_papers')
    # ### end Alembic commands ###
