"""empty message

Revision ID: 3f9d182020a3
Revises: f10a10a9a18e
Create Date: 2025-04-27 09:54:23.975403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f9d182020a3'
down_revision = 'f10a10a9a18e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arxiv_papers', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('question',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llms', schema=None) as batch_op:
        batch_op.alter_column('group',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('arxiv_papers', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('question',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    op.create_table('courses',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('link', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('question',
    sa.Column('question_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('question_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('answer_1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer_1_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer_2_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer_3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer_3_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer_4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer_4_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer_5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer_5_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('question_id', name='question_pkey')
    )
    # ### end Alembic commands ###
