"""empty message

Revision ID: 6b6be6f75f54
Revises: caf6aa62d59e
Create Date: 2025-04-28 01:01:10.485092

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision = '6b6be6f75f54'
down_revision = 'caf6aa62d59e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('question', schema=None) as batch_op:
       batch_op.add_column(sa.Column('vector_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('answer_5_score',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('answer_5',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('answer_4_score',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('answer_4',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('answer_3_score',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('answer_3',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('answer_2_score',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('answer_2',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('answer_1_score',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('answer_1',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('vector_embedding')

    with op.batch_alter_table('llms', schema=None) as batch_op:
        batch_op.alter_column('group',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('category_embeddings_average', schema=None) as batch_op:
        batch_op.alter_column('avg_embedding',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('arxiv_papers', schema=None) as batch_op:
        batch_op.create_index('idx_vector_embedding', ['vector_embedding'], unique=False, postgresql_using='ivfflat')

    op.create_table('courses',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('link', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
