"""empty message

Revision ID: 7b945a4efd75
Revises: 059b16160088
Create Date: 2025-02-20 11:26:15.125812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b945a4efd75'
down_revision = '059b16160088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history_chat')
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_first_message', sa.Boolean(), nullable=True))
        batch_op.alter_column('name_conversation',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_constraint('chat_history_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_constraint('chat_message_history_chat_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'chat_history', ['history_chat_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('chat_message_history_chat_id_fkey', 'chat_history', ['history_chat_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('chat_history_user_id_fkey', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('name_conversation',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('is_first_message')

    op.create_table('history_chat',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bot_response', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='history_chat_pkey')
    )
    op.create_table('courses',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('link', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('question',
    sa.Column('question_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('question_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('answer_1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer_1_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer_2_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer_3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer_3_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer_4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer_4_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer_5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer_5_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('question_id', name='question_pkey')
    )
    # ### end Alembic commands ###
