"""empty message

Revision ID: a3e04e4ae279
Revises: 
Create Date: 2025-02-14 10:42:37.887917

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a3e04e4ae279"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("user", sa.Column("id", sa.Integer(), nullable=False), sa.Column("username", sa.String(length=80), nullable=False), sa.Column("email", sa.String(length=120), nullable=False), sa.Column("password_hash", sa.String(length=128), nullable=False), sa.Column("image_face", sa.String(length=255), nullable=True), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("email"), sa.UniqueConstraint("username"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question",
        sa.Column("question_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("question_title", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("question_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("answer_1", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("answer_1_score", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("answer_2", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("answer_2_score", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("answer_3", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("answer_3_score", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("answer_4", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("answer_4_score", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("answer_5", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("answer_5_score", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("question_id", name="question_pkey"),
    )
    op.drop_table("user")
    # ### end Alembic commands ###
