"""empty message

Revision ID: d23ef3c7bc20
Revises: c08d0ca5e1e9
Create Date: 2025-02-15 23:35:48.224045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd23ef3c7bc20'
down_revision = 'c08d0ca5e1e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_message', sa.String(), nullable=False),
    sa.Column('bot_response', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('link', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('question',
    sa.Column('question_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('question_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('answer_1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer_1_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer_2_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer_3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer_3_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer_4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer_4_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer_5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer_5_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('question_id', name='question_pkey')
    )
    op.drop_table('history_chat')
    # ### end Alembic commands ###
