"""empty message

Revision ID: d83e00a32f0d
Revises: 7b945a4efd75
Create Date: 2025-04-19 12:35:30.743979

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d83e00a32f0d"
down_revision = "7b945a4efd75"
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("avatar_mime", sa.String(length=50), nullable=True))
        batch_op.alter_column("image_face", existing_type=sa.VARCHAR(length=255), type_=sa.Text(), existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column("image_face", existing_type=sa.Text(), type_=sa.VARCHAR(length=255), existing_nullable=True)
        batch_op.drop_column("avatar_mime")
